/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms.Makers;

import Objects.Feedback;
import patientmanagementsystem.PatientManagementSystem;
import patientmanagementsystem.UserTypes.Administrator;
import patientmanagementsystem.UserTypes.Doctor;

/**
 *
 * @author espow
 */
public class FeedbackMakerPage extends javax.swing.JFrame {
    private Doctor doctor;
    private Administrator admin;
    public FeedbackMakerPage(Doctor doctor,Administrator admin) {
        this.doctor = doctor;
        this.admin = admin;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblFeedbackBy = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtFeedback = new javax.swing.JTextArea();
        BtnGiveFeedback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(450, 260));
        setResizable(false);

        LblFeedbackBy.setFont(PatientManagementSystem.getTextFont());
        LblFeedbackBy.setText("Feedback provided by:");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        TxtFeedback.setColumns(20);
        TxtFeedback.setFont(PatientManagementSystem.getTextFont());
        TxtFeedback.setLineWrap(true);
        TxtFeedback.setRows(5);
        TxtFeedback.setWrapStyleWord(true);
        jScrollPane1.setViewportView(TxtFeedback);

        BtnGiveFeedback.setFont(PatientManagementSystem.getTextFont());
        BtnGiveFeedback.setText("Save feedback");
        BtnGiveFeedback.setMaximumSize(new java.awt.Dimension(80, 25));
        BtnGiveFeedback.setMinimumSize(new java.awt.Dimension(80, 25));
        BtnGiveFeedback.setPreferredSize(new java.awt.Dimension(80, 25));
        BtnGiveFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGiveFeedbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LblFeedbackBy)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnGiveFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblFeedbackBy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnGiveFeedback, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnGiveFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGiveFeedbackActionPerformed
        this.doctor.getFeedback().add(new Feedback(this.admin.getUniqueID(),this.TxtFeedback.getText()));
        this.dispose();
    }//GEN-LAST:event_BtnGiveFeedbackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGiveFeedback;
    private javax.swing.JLabel LblFeedbackBy;
    private javax.swing.JTextArea TxtFeedback;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
