/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms.Makers;

import Forms.HomePages.PatientHomePage;
import java.util.ArrayList;
import patientmanagementsystem.PatientManagementSystem;
import Objects.Rating;
import patientmanagementsystem.UserTypes.Doctor;
import patientmanagementsystem.UserTypes.User;

/**
 *
 * @author espow
 */
public class RatingMakerPage extends javax.swing.JFrame {

    PatientHomePage php;
    public RatingMakerPage(PatientHomePage php) {
        this.php = php;
        initComponents();
        loadInDocotrs();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        CbxDoctorSelector = new javax.swing.JComboBox<>();
        LblDoctor = new javax.swing.JLabel();
        LblRating = new javax.swing.JLabel();
        SpinRating = new javax.swing.JSpinner();
        LblComments = new javax.swing.JLabel();
        ScrlComments = new javax.swing.JScrollPane();
        TxtComments = new javax.swing.JTextArea();
        BtnSaveReview = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        CbxDoctorSelector.setFont(PatientManagementSystem.getTextFont());
        CbxDoctorSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxDoctorSelectorActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 15, 15);
        getContentPane().add(CbxDoctorSelector, gridBagConstraints);

        LblDoctor.setFont(PatientManagementSystem.getTextFont());
        LblDoctor.setText("Doctor:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 10);
        getContentPane().add(LblDoctor, gridBagConstraints);

        LblRating.setFont(PatientManagementSystem.getTextFont());
        LblRating.setText("Starts:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 10);
        getContentPane().add(LblRating, gridBagConstraints);

        SpinRating.setFont(PatientManagementSystem.getTextFont());
        SpinRating.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 15, 15);
        getContentPane().add(SpinRating, gridBagConstraints);

        LblComments.setFont(PatientManagementSystem.getTextFont());
        LblComments.setText("Comments:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 10);
        getContentPane().add(LblComments, gridBagConstraints);

        TxtComments.setColumns(20);
        TxtComments.setFont(PatientManagementSystem.getTextFont());
        TxtComments.setLineWrap(true);
        TxtComments.setRows(5);
        TxtComments.setWrapStyleWord(true);
        ScrlComments.setViewportView(TxtComments);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 15, 15);
        getContentPane().add(ScrlComments, gridBagConstraints);

        BtnSaveReview.setFont(PatientManagementSystem.getTextFont());
        BtnSaveReview.setText("Save Review");
        BtnSaveReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveReviewActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        getContentPane().add(BtnSaveReview, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CbxDoctorSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxDoctorSelectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbxDoctorSelectorActionPerformed

    private void BtnSaveReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveReviewActionPerformed
        ArrayList<User> users = PatientManagementSystem.getUsers();
        for(User user: users){
            if(user.getUniqueID().contains("D")){
                    if(this.CbxDoctorSelector.getSelectedItem().toString().contains(user.getFirstName()) &&
                        this.CbxDoctorSelector.getSelectedItem().toString().contains(user.getLastName())){
                        Doctor doctor = (Doctor) user;
                        Rating rating = new Rating((int) this.SpinRating.getValue(),this.TxtComments.getText());
                        doctor.getRatings().add(rating);
                        PatientManagementSystem.saveInformation("test//Data_1.txt");
                        this.php.updateRatingsList();
                        this.dispose();
                    }
            }
        }
    }//GEN-LAST:event_BtnSaveReviewActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSaveReview;
    private javax.swing.JComboBox<String> CbxDoctorSelector;
    private javax.swing.JLabel LblComments;
    private javax.swing.JLabel LblDoctor;
    private javax.swing.JLabel LblRating;
    private javax.swing.JScrollPane ScrlComments;
    private javax.swing.JSpinner SpinRating;
    private javax.swing.JTextArea TxtComments;
    // End of variables declaration//GEN-END:variables

    private void loadInDocotrs() {
        ArrayList<User> users = PatientManagementSystem.getUsers();
         for (int i = 0; i < users.size(); i++) {
            String userID = users.get(i).getUniqueID();
            if(userID.contains("D")){
                this.CbxDoctorSelector.addItem("Dr "+users.get(i).getFirstName()+" "+users.get(i).getLastName());
            }
        }
        if(this.CbxDoctorSelector.getItemCount() == 0) this.CbxDoctorSelector.addItem("No Doctors Loaded");
    }
}
