/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels.Parts;
import Objects.Address;
import javax.swing.JOptionPane;
import patientmanagementsystem.*;
/**
 *
 * @author espow
 */
public class AddressInputPart extends javax.swing.JPanel {
    Address address = null;
    /**
     * Creates new form AddressInputPart
     */
    public AddressInputPart() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        TxtRoadNum = new javax.swing.JTextField();
        TxtRoadName = new javax.swing.JTextField();
        TxtArea = new javax.swing.JTextField();
        TxtCity = new javax.swing.JTextField();
        TxtPostCode = new javax.swing.JTextField();
        LblRoadNum = new javax.swing.JLabel();
        LblRoadName = new javax.swing.JLabel();
        LblArea = new javax.swing.JLabel();
        LblCity = new javax.swing.JLabel();
        LblPostCode = new javax.swing.JLabel();
        BtnInputAddress = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(250, 160));
        setMinimumSize(new java.awt.Dimension(250, 160));
        setPreferredSize(new java.awt.Dimension(250, 160));
        setLayout(new java.awt.GridBagLayout());

        TxtRoadNum.setFont(PatientManagementSystem.getTextFont());
        TxtRoadNum.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TxtRoadNum.setToolTipText("Your user type (P for Patient,\nD for Doctor, A for Administrator,\nS for Secretary) followed\n by 4 numbers.");
        TxtRoadNum.setAutoscrolls(false);
        TxtRoadNum.setMaximumSize(new java.awt.Dimension(100, 22));
        TxtRoadNum.setMinimumSize(new java.awt.Dimension(100, 22));
        TxtRoadNum.setName("TxtRoadNum"); // NOI18N
        TxtRoadNum.setPreferredSize(new java.awt.Dimension(100, 22));
        TxtRoadNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtRoadNumActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(TxtRoadNum, gridBagConstraints);

        TxtRoadName.setFont(PatientManagementSystem.getTextFont());
        TxtRoadName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TxtRoadName.setToolTipText("Your user type (P for Patient,\nD for Doctor, A for Administrator,\nS for Secretary) followed\n by 4 numbers.");
        TxtRoadName.setAutoscrolls(false);
        TxtRoadName.setMaximumSize(new java.awt.Dimension(100, 22));
        TxtRoadName.setMinimumSize(new java.awt.Dimension(100, 22));
        TxtRoadName.setName("txtUniqueID"); // NOI18N
        TxtRoadName.setPreferredSize(new java.awt.Dimension(100, 22));
        TxtRoadName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtRoadNameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(TxtRoadName, gridBagConstraints);

        TxtArea.setFont(PatientManagementSystem.getTextFont());
        TxtArea.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TxtArea.setToolTipText("Your user type (P for Patient,\nD for Doctor, A for Administrator,\nS for Secretary) followed\n by 4 numbers.");
        TxtArea.setAutoscrolls(false);
        TxtArea.setMaximumSize(new java.awt.Dimension(100, 22));
        TxtArea.setMinimumSize(new java.awt.Dimension(100, 22));
        TxtArea.setName("txtUniqueID"); // NOI18N
        TxtArea.setPreferredSize(new java.awt.Dimension(100, 22));
        TxtArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtAreaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(TxtArea, gridBagConstraints);

        TxtCity.setFont(PatientManagementSystem.getTextFont());
        TxtCity.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TxtCity.setToolTipText("Your user type (P for Patient,\nD for Doctor, A for Administrator,\nS for Secretary) followed\n by 4 numbers.");
        TxtCity.setAutoscrolls(false);
        TxtCity.setMaximumSize(new java.awt.Dimension(100, 22));
        TxtCity.setMinimumSize(new java.awt.Dimension(100, 22));
        TxtCity.setName("txtUniqueID"); // NOI18N
        TxtCity.setPreferredSize(new java.awt.Dimension(100, 22));
        TxtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCityActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(TxtCity, gridBagConstraints);

        TxtPostCode.setFont(PatientManagementSystem.getTextFont());
        TxtPostCode.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TxtPostCode.setToolTipText("Your user type (P for Patient,\nD for Doctor, A for Administrator,\nS for Secretary) followed\n by 4 numbers.");
        TxtPostCode.setAutoscrolls(false);
        TxtPostCode.setMaximumSize(new java.awt.Dimension(150, 22));
        TxtPostCode.setMinimumSize(new java.awt.Dimension(150, 22));
        TxtPostCode.setName("txtUniqueID"); // NOI18N
        TxtPostCode.setPreferredSize(new java.awt.Dimension(150, 22));
        TxtPostCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPostCodeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(TxtPostCode, gridBagConstraints);

        LblRoadNum.setFont(PatientManagementSystem.getTextFont());
        LblRoadNum.setText("Road Num:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        add(LblRoadNum, gridBagConstraints);

        LblRoadName.setFont(PatientManagementSystem.getTextFont());
        LblRoadName.setText("Road Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(LblRoadName, gridBagConstraints);

        LblArea.setFont(PatientManagementSystem.getTextFont());
        LblArea.setText("Area:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        add(LblArea, gridBagConstraints);

        LblCity.setFont(PatientManagementSystem.getTextFont());
        LblCity.setText("City:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        add(LblCity, gridBagConstraints);

        LblPostCode.setFont(PatientManagementSystem.getTextFont());
        LblPostCode.setText("Post Code:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        add(LblPostCode, gridBagConstraints);

        BtnInputAddress.setFont(PatientManagementSystem.getTextFont());
        BtnInputAddress.setText("Input Address");
        BtnInputAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInputAddressActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        add(BtnInputAddress, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void TxtRoadNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtRoadNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtRoadNumActionPerformed

    private void TxtRoadNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtRoadNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtRoadNameActionPerformed

    private void TxtAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtAreaActionPerformed

    private void TxtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCityActionPerformed

    private void TxtPostCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPostCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPostCodeActionPerformed

    private void BtnInputAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInputAddressActionPerformed
        updateAddress();
    }//GEN-LAST:event_BtnInputAddressActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnInputAddress;
    private javax.swing.JLabel LblArea;
    private javax.swing.JLabel LblCity;
    private javax.swing.JLabel LblPostCode;
    private javax.swing.JLabel LblRoadName;
    private javax.swing.JLabel LblRoadNum;
    private javax.swing.JTextField TxtArea;
    private javax.swing.JTextField TxtCity;
    private javax.swing.JTextField TxtPostCode;
    private javax.swing.JTextField TxtRoadName;
    private javax.swing.JTextField TxtRoadNum;
    // End of variables declaration//GEN-END:variables

    public void updateAddress() {
        if(Address.checkPostCodeValid(this.TxtPostCode.getText()))
            if(checkAddressFull()){try{
                Integer.parseInt(this.TxtRoadNum.getText());
                this.address = new Address(this.TxtRoadNum.getText(), this.TxtRoadName.getText(), this.TxtArea.getText(), this.TxtCity.getText(), this.TxtPostCode.getText());
            } catch(Exception e){
                JOptionPane.showMessageDialog(null,
                            "The Road number is not a valid integer",
                            "Incorrect RoadNumber",
                            JOptionPane.ERROR_MESSAGE);
            }}
            else JOptionPane.showMessageDialog(null,
                            "Not all of the address is full",
                            "Invalid Address",
                            JOptionPane.ERROR_MESSAGE);
        else JOptionPane.showMessageDialog(null,
                            "The Post Code is invalid",
                            "Invalid Post Code",
                            JOptionPane.ERROR_MESSAGE);
    }
        
    public Address getAddress(){
        return address;
    }
    
    private boolean checkAddressFull(){
        return !("".equals(this.TxtRoadNum.getText()) || this.TxtRoadNum.getText() == null ||
                "".equals(this.TxtRoadName.getText()) || this.TxtRoadName.getText() == null ||
                "".equals(this.TxtArea.getText()) || this.TxtArea.getText() == null ||
                "".equals(this.TxtCity.getText()) || this.TxtCity.getText() == null ||
                "".equals(this.TxtPostCode.getText()) || this.TxtPostCode.getText() == null);
    }
}
