/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels.Parts;
import java.text.SimpleDateFormat;
import java.util.Date;
import patientmanagementsystem.PatientManagementSystem;
/**
 *
 * @author espow
 */
public class DateSelectPart extends javax.swing.JPanel {
    Date date = null;
    /**
     * Creates new form DateSelectPanel
     */
    public DateSelectPart() {
        initComponents();
        updateDate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        LblPickDate = new javax.swing.JLabel();
        SpinMonth = new javax.swing.JSpinner();
        SpinYear = new javax.swing.JSpinner();
        SpinDay = new javax.swing.JSpinner();
        LblSlash = new javax.swing.JLabel();
        LblSlash1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(170, 60));
        setMinimumSize(new java.awt.Dimension(170, 60));
        setPreferredSize(new java.awt.Dimension(170, 60));
        setLayout(new java.awt.GridBagLayout());

        LblPickDate.setFont(PatientManagementSystem.getTextFont());
        LblPickDate.setText("Pick Date:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(LblPickDate, gridBagConstraints);

        SpinMonth.setFont(PatientManagementSystem.getTextFont());
        SpinMonth.setModel(new javax.swing.SpinnerListModel(new String[] {"01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"}));
        SpinMonth.setEditor(new javax.swing.JSpinner.ListEditor(SpinMonth));
        SpinMonth.setPreferredSize(new java.awt.Dimension(40, 22));
        SpinMonth.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SpinMonthStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(SpinMonth, gridBagConstraints);

        SpinYear.setFont(PatientManagementSystem.getTextFont());
        SpinYear.setModel(new javax.swing.SpinnerListModel(new String[] {"1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021"}));
        SpinYear.setEditor(new javax.swing.JSpinner.ListEditor(SpinYear));
        SpinYear.setPreferredSize(new java.awt.Dimension(60, 22));
        SpinYear.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SpinYearStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(SpinYear, gridBagConstraints);

        SpinDay.setFont(PatientManagementSystem.getTextFont());
        SpinDay.setModel(new javax.swing.SpinnerListModel(new String[] {"01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31"}));
        SpinDay.setEditor(new javax.swing.JSpinner.ListEditor(SpinDay));
        SpinDay.setMinimumSize(new java.awt.Dimension(40, 22));
        SpinDay.setPreferredSize(new java.awt.Dimension(40, 22));
        SpinDay.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SpinDayStateChanged(evt);
            }
        });
        SpinDay.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                SpinDayPropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(SpinDay, gridBagConstraints);

        LblSlash.setFont(PatientManagementSystem.getTextFont());
        LblSlash.setText("/");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(LblSlash, gridBagConstraints);

        LblSlash1.setFont(PatientManagementSystem.getTextFont());
        LblSlash1.setText("/");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(LblSlash1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void SpinMonthStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SpinMonthStateChanged
        setDayToValid();
    }//GEN-LAST:event_SpinMonthStateChanged

    private void SpinYearStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SpinYearStateChanged
        setDayToValid();
    }//GEN-LAST:event_SpinYearStateChanged

    private void SpinDayStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SpinDayStateChanged
        setDayToValid();
    }//GEN-LAST:event_SpinDayStateChanged

    private void SpinDayPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_SpinDayPropertyChange
        // Was unable to remove it after a mis-click
    }//GEN-LAST:event_SpinDayPropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblPickDate;
    private javax.swing.JLabel LblSlash;
    private javax.swing.JLabel LblSlash1;
    private javax.swing.JSpinner SpinDay;
    private javax.swing.JSpinner SpinMonth;
    private javax.swing.JSpinner SpinYear;
    // End of variables declaration//GEN-END:variables

    private boolean checkDateValid(){
        boolean result = false;
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        Date date = new Date(this.SpinYear.getValue().toString()+"/"+this.SpinMonth.getValue().toString()+"/"+this.SpinDay.getValue().toString());
        if((this.SpinDay.getValue().toString()+"/"+this.SpinMonth.getValue().toString()+"/"+this.SpinYear.getValue().toString()).equals(dateFormat.format(date))) return true;
        else return result;
    }
    
    private void setDayToValid(){
        if(!checkDateValid()){
            int month = Integer.parseInt(this.SpinMonth.getValue().toString());
            if(month<=7){
                if(month == 2)
                    if((Integer.parseInt(this.SpinYear.getValue().toString())%4 == 0)) this.SpinDay.setValue("29");
                    else this.SpinDay.setValue("28");
                else if (month%2 == 0) this.SpinDay.setValue("30");
                else this.SpinDay.setValue("31");
            }
            else{
                if (month%2 == 0) this.SpinDay.setValue("31");
                else this.SpinDay.setValue("30");
            }
        }
        updateDate();
    }
    
    private void updateDate() {
        this.date = new Date(this.SpinYear.getValue().toString()+"/"+this.SpinMonth.getValue().toString()+"/"+this.SpinDay.getValue().toString()+" 00:00");
    }
    
    public Date getDate() {
        return this.date;
    }
}
