/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms.Requesters;

import Forms.HomePages.PatientHomePage;
import Forms.HomePages.SecretaryHomePage;
import java.util.Date;
import Objects.Appointment;
import patientmanagementsystem.PatientManagementSystem;
import patientmanagementsystem.UserTypes.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author espow
 */
public class PatientAppointmentRequester extends javax.swing.JFrame {
    PatientHomePage php;
    Date date;
    Doctor doctor;
    public PatientAppointmentRequester(PatientHomePage php) {
        this.php = php;
        initComponents();
        this.LblPatientName.setText(this.LblPatientName.getText()+this.php.getPatient().getFirstName()+" "+this.php.getPatient().getLastName());
        loadDoctors();
        updateDate();
        updateDoctor();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblPatientName = new javax.swing.JLabel();
        BtnCancel = new javax.swing.JButton();
        BtnRequest = new javax.swing.JButton();
        CoBoDoctorSelector = new javax.swing.JComboBox<>();
        LblPickDoctor = new javax.swing.JLabel();
        TxtAddress = new javax.swing.JTextArea();
        LblDoctorRating = new javax.swing.JLabel();
        Date lastDate = new Date();
        lastDate.setYear(lastDate.getYear()+2);
        dateSelectPart1 = new Panels.Parts.DateSelectPart(new Date(),lastDate);
        LblPickTime = new javax.swing.JLabel();
        LblColon = new javax.swing.JLabel();
        SpinHour = new javax.swing.JSpinner();
        SpinMinutes = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Request an Appointment");
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(600, 300));
        setResizable(false);

        LblPatientName.setFont(PatientManagementSystem.getTextFont());
        LblPatientName.setText("Patient: ");

        BtnCancel.setFont(PatientManagementSystem.getTextFont());
        BtnCancel.setText("Cancel");
        BtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelActionPerformed(evt);
            }
        });

        BtnRequest.setFont(PatientManagementSystem.getTextFont());
        BtnRequest.setText("Request this Appoinment");
        BtnRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRequestActionPerformed(evt);
            }
        });

        CoBoDoctorSelector.setFont(PatientManagementSystem.getTextFont());
        CoBoDoctorSelector.setMaximumSize(new java.awt.Dimension(127, 32767));
        CoBoDoctorSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoBoDoctorSelectorActionPerformed(evt);
            }
        });

        LblPickDoctor.setFont(PatientManagementSystem.getTextFont());
        LblPickDoctor.setText("Pick Doctor: ");

        TxtAddress.setEditable(false);
        TxtAddress.setBackground(javax.swing.UIManager.getDefaults().getColor("Panel.background"));
        TxtAddress.setColumns(20);
        TxtAddress.setFont(PatientManagementSystem.getTextFont());
        TxtAddress.setLineWrap(true);
        TxtAddress.setRows(4);
        TxtAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TxtAddress.setMinimumSize(new java.awt.Dimension(200, 20));

        LblDoctorRating.setFont(PatientManagementSystem.getTextFont());
        LblDoctorRating.setText("Rating: N/A");
        LblDoctorRating.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        LblPickTime.setFont(PatientManagementSystem.getTextFont());
        LblPickTime.setText("Pick Time:");

        LblColon.setFont(PatientManagementSystem.getTextFont());
        LblColon.setText(":");

        SpinHour.setFont(PatientManagementSystem.getTextFont());
        SpinHour.setModel(new javax.swing.SpinnerListModel(new String[] {"08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"}));
        SpinHour.setEditor(new javax.swing.JSpinner.ListEditor(SpinHour));
        SpinHour.setMinimumSize(new java.awt.Dimension(40, 22));
        SpinHour.setPreferredSize(new java.awt.Dimension(40, 22));
        SpinHour.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SpinHourStateChanged(evt);
            }
        });

        SpinMinutes.setFont(PatientManagementSystem.getTextFont());
        SpinMinutes.setModel(new javax.swing.SpinnerListModel(new String[] {"00", "15", "30", "45"}));
        SpinMinutes.setEditor(new javax.swing.JSpinner.ListEditor(SpinMinutes));
        SpinMinutes.setMinimumSize(new java.awt.Dimension(40, 22));
        SpinMinutes.setPreferredSize(new java.awt.Dimension(40, 22));
        SpinMinutes.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SpinMinutesStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dateSelectPart1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblPickTime)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SpinHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LblColon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SpinMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LblDoctorRating, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(119, 119, 119))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LblPickDoctor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CoBoDoctorSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(TxtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(BtnCancel)
                        .addGap(122, 122, 122)
                        .addComponent(BtnRequest))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LblPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblPatientName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblPickDoctor)
                            .addComponent(CoBoDoctorSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblDoctorRating))
                    .addComponent(TxtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dateSelectPart1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(LblPickTime)
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SpinHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblColon)
                            .addComponent(SpinMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCancel)
                    .addComponent(BtnRequest))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnCancelActionPerformed

    private void BtnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRequestActionPerformed
        try{
            updateDate();
            if(doctor != null ){
                if(!checkIfBusy(this.php.getPatient(),doctor,date)){
                    ArrayList<Appointment> appointments = PatientManagementSystem.getAppointments();
                    appointments.add(new Appointment(this.php.getPatient(),doctor,"Request",date));
                    PatientManagementSystem.setAppointments(appointments);
                    this.php.updateAppointmentsList(php.getPatient().getAppointments());
                    PatientManagementSystem.saveInformation(PatientManagementSystem.getFile());
                    dispose();
                }
                else{
                    JOptionPane.showMessageDialog(null, "The doctor or patient is busy\nat this time");
                }
            }
            else JOptionPane.showMessageDialog(null, "No doctor is selected");
        } catch (Exception e){
        }
    }//GEN-LAST:event_BtnRequestActionPerformed

    private void CoBoDoctorSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoBoDoctorSelectorActionPerformed
        updateDoctor();
    }//GEN-LAST:event_CoBoDoctorSelectorActionPerformed

    private void SpinHourStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SpinHourStateChanged
        updateDate();
    }//GEN-LAST:event_SpinHourStateChanged

    private void SpinMinutesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SpinMinutesStateChanged
        updateDate();
    }//GEN-LAST:event_SpinMinutesStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancel;
    private javax.swing.JButton BtnRequest;
    public javax.swing.JComboBox<String> CoBoDoctorSelector;
    private javax.swing.JLabel LblColon;
    private javax.swing.JLabel LblDoctorRating;
    private javax.swing.JLabel LblPatientName;
    private javax.swing.JLabel LblPickDoctor;
    private javax.swing.JLabel LblPickTime;
    private javax.swing.JSpinner SpinHour;
    private javax.swing.JSpinner SpinMinutes;
    private javax.swing.JTextArea TxtAddress;
    private Panels.Parts.DateSelectPart dateSelectPart1;
    // End of variables declaration//GEN-END:variables

    private boolean checkIfBusy(Patient patient, Doctor doctor, Date date) {
        boolean busy = false;
        for (Appointment appointment : PatientManagementSystem.getAppointments()) {
            if (appointment.getDoctor() == doctor || appointment.getPatient() == patient){
                if(appointment.getDateTime().equals(date)) busy = true;
            }
        }
        return busy;
    }
    
    private void loadDoctors() {
        for (int i = 0; i < PatientManagementSystem.getUsers().size(); i++) {
            String userID = PatientManagementSystem.getUsers().get(i).getUniqueID();
            if(userID.contains("D")){
                this.CoBoDoctorSelector.addItem("Dr "+PatientManagementSystem.getUsers().get(i).getFirstName()+" "+PatientManagementSystem.getUsers().get(i).getLastName());
            }
        }
        if(this.CoBoDoctorSelector.getItemCount() == 0) this.CoBoDoctorSelector.addItem("No Doctors Loaded");
    }
    
    private void updateDate() {
        date = this.dateSelectPart1.getDate();
        date.setHours(Integer.parseInt(this.SpinHour.getValue().toString()));
        date.setMinutes(Integer.parseInt(this.SpinMinutes.getValue().toString()));
    }

    private void updateDoctor() {
        for (int i = 0; i < PatientManagementSystem.getUsers().size(); i++) {
            String userID = PatientManagementSystem.getUsers().get(i).getUniqueID();
            if(userID.contains("D")){
                if(this.CoBoDoctorSelector.getSelectedItem().toString().contains(PatientManagementSystem.getUsers().get(i).getFirstName()) &&
                    this.CoBoDoctorSelector.getSelectedItem().toString().contains(PatientManagementSystem.getUsers().get(i).getLastName())){
                    this.doctor = (Doctor) PatientManagementSystem.getUsers().get(i);
                }
            }
        }
        if(this.doctor != null){
            this.LblDoctorRating.setText("Rating: "+doctor.getAverageRating()+"/5");
            this.TxtAddress.setText(doctor.getAddress().getFormattedAddress());
        }
        else{
            this.LblDoctorRating.setText("Rating: N/A");
            if(this.TxtAddress.getText() == null || this.TxtAddress.getText() == "") this.TxtAddress.setText("No Doctors Loaded");
        }
    }
}
