/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;
import Forms.HomePages.DoctorHomePage;
import Forms.HomePages.SecretaryHomePage;
import Objects.Medicine;
import Panels.MedicineOrderPanel;
import patientmanagementsystem.PatientManagementSystem;

/**
 *
 * @author espow
 */
public class MakeOrderPage extends javax.swing.JFrame {
    private SecretaryHomePage shp = null;
    private DoctorHomePage dhp = null;
    public MakeOrderPage(SecretaryHomePage shp) {
        this.shp = shp;
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public MakeOrderPage(DoctorHomePage dhp) {
        this.dhp = dhp;
        initComponents();
        setLocationRelativeTo(null);
        this.BtnOrder.setText("Request Order");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnCancel = new javax.swing.JButton();
        BtnOrder = new javax.swing.JButton();
        medicineOrderPanel1 = new Panels.MedicineOrderPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Order Medicine");
        setMaximumSize(new java.awt.Dimension(350, 125));
        setMinimumSize(new java.awt.Dimension(350, 125));
        setResizable(false);

        BtnCancel.setFont(PatientManagementSystem.getTextFont());
        BtnCancel.setText("Cancel");
        BtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelActionPerformed(evt);
            }
        });

        BtnOrder.setFont(PatientManagementSystem.getTextFont());
        BtnOrder.setText("Order");
        BtnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(medicineOrderPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(medicineOrderPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCancel)
                    .addComponent(BtnOrder))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnCancelActionPerformed

    private void BtnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOrderActionPerformed
        if(shp != null){
            boolean notFound = true;
            for(Medicine medicine : PatientManagementSystem.getMedicines()){
                if(medicine.getMedicineName().equalsIgnoreCase(this.medicineOrderPanel1.getMedicineName())){
                    medicine.setOrdered(medicine.getOrdered() + this.medicineOrderPanel1.getQuantity());
                    notFound = false;
                }
            }
            if(notFound)PatientManagementSystem.getMedicines().add(new Medicine(
                    this.medicineOrderPanel1.getMedicineName(),0,this.medicineOrderPanel1.getQuantity(),0));
            shp.updateAll();
        } else if(dhp!= null){
            boolean notFound = true;
            for(Medicine medicine : PatientManagementSystem.getMedicines()){
                if(medicine.getMedicineName().equalsIgnoreCase(this.medicineOrderPanel1.getMedicineName())){
                    medicine.setRequestedOrdered(medicine.getRequestedOrdered() + this.medicineOrderPanel1.getQuantity());
                    notFound = false;
                }
            }
            if(notFound)PatientManagementSystem.getMedicines().add(new Medicine(
                    this.medicineOrderPanel1.getMedicineName(),0,0,this.medicineOrderPanel1.getQuantity()));
            dhp.updateAll();
        }
        PatientManagementSystem.saveInformation(PatientManagementSystem.getFile());
        this.dispose();
    }//GEN-LAST:event_BtnOrderActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancel;
    private javax.swing.JButton BtnOrder;
    private Panels.MedicineOrderPanel medicineOrderPanel1;
    // End of variables declaration//GEN-END:variables
}
