/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels.ContainedComponents;
import Objects.Appointment;
import patientmanagementsystem.*;
/**
 *
 * @author espow
 */
public class AppointmentPanel extends javax.swing.JPanel {

    private final Appointment Appointment;
    
    /**
     * Creates new form AppointmentPanel
     * @param Appointment
     */
    public AppointmentPanel(Appointment Appointment) {
        initComponents();
        this.Appointment = Appointment;
        fillInformation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        LblTime = new javax.swing.JLabel();
        LblDoctorName = new javax.swing.JLabel();
        LblDoctorRating = new javax.swing.JLabel();
        LblPatientName = new javax.swing.JLabel();
        TxtAddress = new javax.swing.JTextArea();
        LblStatus = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setFont(PatientManagementSystem.getTextFont());
        setMaximumSize(new java.awt.Dimension(600, 100));
        setMinimumSize(new java.awt.Dimension(600, 100));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(600, 100));
        setLayout(new java.awt.GridBagLayout());

        LblTime.setFont(PatientManagementSystem.getTextFont());
        LblTime.setText("Date:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 5, 5);
        add(LblTime, gridBagConstraints);

        LblDoctorName.setFont(PatientManagementSystem.getTextFont());
        LblDoctorName.setText("Doctor: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 10, 5);
        add(LblDoctorName, gridBagConstraints);

        LblDoctorRating.setFont(PatientManagementSystem.getTextFont());
        LblDoctorRating.setText("Rating: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 10, 5);
        add(LblDoctorRating, gridBagConstraints);

        LblPatientName.setFont(PatientManagementSystem.getTextFont());
        LblPatientName.setText("Patient: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 5, 5);
        add(LblPatientName, gridBagConstraints);

        TxtAddress.setEditable(false);
        TxtAddress.setBackground(javax.swing.UIManager.getDefaults().getColor("Panel.background"));
        TxtAddress.setColumns(20);
        TxtAddress.setFont(PatientManagementSystem.getTextFont());
        TxtAddress.setLineWrap(true);
        TxtAddress.setRows(4);
        TxtAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TxtAddress.setMaximumSize(new java.awt.Dimension(150, 75));
        TxtAddress.setMinimumSize(new java.awt.Dimension(102, 75));
        TxtAddress.setPreferredSize(new java.awt.Dimension(102, 75));
        TxtAddress.setRequestFocusEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 5);
        add(TxtAddress, gridBagConstraints);

        LblStatus.setFont(PatientManagementSystem.getTextFont());
        LblStatus.setText("Status: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 10);
        add(LblStatus, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblDoctorName;
    private javax.swing.JLabel LblDoctorRating;
    private javax.swing.JLabel LblPatientName;
    private javax.swing.JLabel LblStatus;
    private javax.swing.JLabel LblTime;
    private javax.swing.JTextArea TxtAddress;
    // End of variables declaration//GEN-END:variables

    private void fillInformation() {
        LblPatientName.setText(LblPatientName.getText()+this.Appointment.getPatient().getFirstName()+" "+this.Appointment.getPatient().getLastName());
        LblTime.setText(LblTime.getText()+PatientManagementSystem.getFormat().format(this.Appointment.getDateTime()));
        LblDoctorName.setText(LblDoctorName.getText()+this.Appointment.getDoctor().getFirstName()+" "+this.Appointment.getDoctor().getLastName());
        LblDoctorRating.setText(LblDoctorRating.getText()+this.Appointment.getDoctor().getAverageRating());
        LblStatus.setText(LblStatus.getText()+this.Appointment.getStatus());
        TxtAddress.setText(this.Appointment.getDoctor().getAddress().getFormattedAddress());
    }
}
