/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels.ContainedComponents;

import Objects.Feedback;
import patientmanagementsystem.PatientManagementSystem;

/**
 *
 * @author espow
 */
public class FeedbackPanel extends javax.swing.JPanel {
    private final Feedback feedback;
    public FeedbackPanel(Feedback feedback) {
        this.feedback = feedback;
        initComponents();
        fillData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblFeedbackBy = new javax.swing.JLabel();
        LblDateOfFeedback = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtFeedback = new javax.swing.JTextArea();

        setMaximumSize(new java.awt.Dimension(700, 100));
        setMinimumSize(new java.awt.Dimension(700, 100));

        LblFeedbackBy.setFont(PatientManagementSystem.getTextFont());
        LblFeedbackBy.setText("Provided by:");

        LblDateOfFeedback.setFont(PatientManagementSystem.getTextFont());
        LblDateOfFeedback.setText("Date:");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(160, 94));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(160, 94));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(160, 94));

        TxtFeedback.setEditable(false);
        TxtFeedback.setColumns(20);
        TxtFeedback.setFont(PatientManagementSystem.getTextFont());
        TxtFeedback.setLineWrap(true);
        TxtFeedback.setRows(5);
        TxtFeedback.setWrapStyleWord(true);
        TxtFeedback.setMaximumSize(new java.awt.Dimension(160, 1000));
        TxtFeedback.setMinimumSize(new java.awt.Dimension(160, 94));
        TxtFeedback.setPreferredSize(new java.awt.Dimension(160, 94));
        jScrollPane1.setViewportView(TxtFeedback);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblFeedbackBy)
                    .addComponent(LblDateOfFeedback))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LblFeedbackBy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(LblDateOfFeedback)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(10, 10, 10))))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblDateOfFeedback;
    private javax.swing.JLabel LblFeedbackBy;
    private javax.swing.JTextArea TxtFeedback;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void fillData() {
        this.LblFeedbackBy.setText(this.LblFeedbackBy.getText()+this.feedback.getFeedbackBy());
        this.LblDateOfFeedback.setText(this.LblDateOfFeedback.getText()+this.feedback.getFeedbackBy());
        this.TxtFeedback.setText(this.feedback.getFeedback());
    }
}
