/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels.ContainedComponents;

import Objects.Medicine;
import patientmanagementsystem.PatientManagementSystem;

/**
 *
 * @author espow
 */
public class MedicinePanel extends javax.swing.JPanel {
    private final Medicine medicine;
    public MedicinePanel(Medicine medicine) {
        this.medicine = medicine;
        initComponents();
        fillData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblMedicineName = new javax.swing.JLabel();
        LblStock = new javax.swing.JLabel();
        LblOrdered = new javax.swing.JLabel();
        LblRequestedOrder = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(600, 100));
        setMinimumSize(new java.awt.Dimension(600, 100));
        setPreferredSize(new java.awt.Dimension(600, 100));

        LblMedicineName.setFont(PatientManagementSystem.getTextFont());
        LblMedicineName.setText("Medicine Name: ");

        LblStock.setFont(PatientManagementSystem.getTextFont());
        LblStock.setText("Stock: ");

        LblOrdered.setFont(PatientManagementSystem.getTextFont());
        LblOrdered.setText("Ordered: ");

        LblRequestedOrder.setFont(PatientManagementSystem.getTextFont());
        LblRequestedOrder.setText("Requested Order: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblMedicineName)
                .addGap(37, 37, 37)
                .addComponent(LblStock)
                .addGap(38, 38, 38)
                .addComponent(LblOrdered)
                .addGap(39, 39, 39)
                .addComponent(LblRequestedOrder)
                .addContainerGap(192, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblMedicineName)
                    .addComponent(LblStock)
                    .addComponent(LblOrdered)
                    .addComponent(LblRequestedOrder))
                .addContainerGap(45, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblMedicineName;
    private javax.swing.JLabel LblOrdered;
    private javax.swing.JLabel LblRequestedOrder;
    private javax.swing.JLabel LblStock;
    // End of variables declaration//GEN-END:variables

    private void fillData() {
        LblMedicineName.setText(LblMedicineName.getText()+ medicine.getMedicineName());
        LblOrdered.setText(LblOrdered.getText() + medicine.getOrdered());
        LblRequestedOrder.setText(LblRequestedOrder.getText() + medicine.getRequestedOrdered());
        LblStock.setText(LblStock.getText() + medicine.getStock());
    }
}
