/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels.ContainedComponents;
import javax.swing.table.DefaultTableModel;
import Objects.Prescription;

import patientmanagementsystem.PatientManagementSystem;
import Objects.PrescribedMedicine;

/**
 *
 * @author espow
 */
public class PrescriptionPanel extends javax.swing.JPanel {
    private final Prescription prescription;
    public PrescriptionPanel(Prescription prescription) {
        this.prescription = prescription;
        initComponents();
        fillData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        LblPatientName = new javax.swing.JLabel();
        LblDoctorName = new javax.swing.JLabel();
        TxtDoctorAddress = new javax.swing.JTextArea();
        TxtPatientAddress = new javax.swing.JTextArea();
        LblPatientSex = new javax.swing.JLabel();
        LblPatientAge = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtNotes = new javax.swing.JTextArea();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        LblNotes = new javax.swing.JLabel();
        LblPatientAddress = new javax.swing.JLabel();
        LblDoctorAddress = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TblMedicines = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setMaximumSize(new java.awt.Dimension(650, 350));
        setMinimumSize(new java.awt.Dimension(650, 350));
        setPreferredSize(new java.awt.Dimension(650, 350));
        setLayout(new java.awt.GridBagLayout());

        LblPatientName.setFont(PatientManagementSystem.getTextFont());
        LblPatientName.setText("Patient: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        add(LblPatientName, gridBagConstraints);

        LblDoctorName.setFont(PatientManagementSystem.getTextFont());
        LblDoctorName.setText("Doctor: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        add(LblDoctorName, gridBagConstraints);

        TxtDoctorAddress.setEditable(false);
        TxtDoctorAddress.setBackground(javax.swing.UIManager.getDefaults().getColor("Panel.background"));
        TxtDoctorAddress.setColumns(20);
        TxtDoctorAddress.setFont(PatientManagementSystem.getTextFont());
        TxtDoctorAddress.setLineWrap(true);
        TxtDoctorAddress.setRows(4);
        TxtDoctorAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TxtDoctorAddress.setMaximumSize(new java.awt.Dimension(150, 80));
        TxtDoctorAddress.setMinimumSize(new java.awt.Dimension(102, 80));
        TxtDoctorAddress.setPreferredSize(new java.awt.Dimension(102, 80));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(TxtDoctorAddress, gridBagConstraints);

        TxtPatientAddress.setEditable(false);
        TxtPatientAddress.setBackground(javax.swing.UIManager.getDefaults().getColor("Panel.background"));
        TxtPatientAddress.setColumns(20);
        TxtPatientAddress.setFont(PatientManagementSystem.getTextFont());
        TxtPatientAddress.setLineWrap(true);
        TxtPatientAddress.setRows(4);
        TxtPatientAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TxtPatientAddress.setMaximumSize(new java.awt.Dimension(150, 80));
        TxtPatientAddress.setMinimumSize(new java.awt.Dimension(102, 80));
        TxtPatientAddress.setPreferredSize(new java.awt.Dimension(102, 80));
        TxtPatientAddress.setRequestFocusEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        add(TxtPatientAddress, gridBagConstraints);

        LblPatientSex.setFont(PatientManagementSystem.getTextFont());
        LblPatientSex.setText("Sex: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        add(LblPatientSex, gridBagConstraints);

        LblPatientAge.setFont(PatientManagementSystem.getTextFont());
        LblPatientAge.setText("Age: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        add(LblPatientAge, gridBagConstraints);

        jSeparator3.setMaximumSize(new java.awt.Dimension(645, 1));
        jSeparator3.setMinimumSize(new java.awt.Dimension(645, 1));
        jSeparator3.setPreferredSize(new java.awt.Dimension(645, 1));
        jSeparator3.setVerifyInputWhenFocusTarget(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(jSeparator3, gridBagConstraints);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(400, 100));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(400, 100));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(400, 100));

        TxtNotes.setEditable(false);
        TxtNotes.setColumns(20);
        TxtNotes.setFont(PatientManagementSystem.getTextFont());
        TxtNotes.setLineWrap(true);
        TxtNotes.setRows(5);
        TxtNotes.setWrapStyleWord(true);
        TxtNotes.setMaximumSize(new java.awt.Dimension(400, 2147483647));
        TxtNotes.setMinimumSize(new java.awt.Dimension(400, 100));
        TxtNotes.setPreferredSize(new java.awt.Dimension(400, 100));
        TxtNotes.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(TxtNotes);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(jScrollPane1, gridBagConstraints);

        jSeparator4.setMaximumSize(new java.awt.Dimension(645, 1));
        jSeparator4.setMinimumSize(new java.awt.Dimension(645, 1));
        jSeparator4.setPreferredSize(new java.awt.Dimension(645, 1));
        jSeparator4.setVerifyInputWhenFocusTarget(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(jSeparator4, gridBagConstraints);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator5.setPreferredSize(new java.awt.Dimension(1, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        add(jSeparator5, gridBagConstraints);

        LblNotes.setFont(PatientManagementSystem.getTextFont());
        LblNotes.setText("Notes:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        add(LblNotes, gridBagConstraints);

        LblPatientAddress.setFont(PatientManagementSystem.getTextFont());
        LblPatientAddress.setText("Address: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        add(LblPatientAddress, gridBagConstraints);

        LblDoctorAddress.setFont(PatientManagementSystem.getTextFont());
        LblDoctorAddress.setText("Address: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        add(LblDoctorAddress, gridBagConstraints);

        jScrollPane2.setMaximumSize(new java.awt.Dimension(640, 100));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(640, 100));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(640, 100));

        TblMedicines.setFont(PatientManagementSystem.getTextFont());
        TblMedicines.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TblMedicines.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(TblMedicines);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(jScrollPane2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblDoctorAddress;
    private javax.swing.JLabel LblDoctorName;
    private javax.swing.JLabel LblNotes;
    private javax.swing.JLabel LblPatientAddress;
    private javax.swing.JLabel LblPatientAge;
    private javax.swing.JLabel LblPatientName;
    private javax.swing.JLabel LblPatientSex;
    private javax.swing.JTable TblMedicines;
    private javax.swing.JTextArea TxtDoctorAddress;
    private javax.swing.JTextArea TxtNotes;
    private javax.swing.JTextArea TxtPatientAddress;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables

    private void fillData() {
        fillPatientData();
        fillDoctorData();
        fillNotes();
        fillMedicines();
    }

    private void fillPatientData() {
        this.LblPatientName.setText(this.LblPatientName.getText()+this.prescription.getIssueTo().getFirstName()+" "+this.prescription.getIssueTo().getLastName());
        this.LblPatientAge.setText(this.LblPatientAge.getText()+" "+this.prescription.getIssueTo().getAge());
        this.LblPatientSex.setText(this.LblPatientSex.getText()+" "+ this.prescription.getIssueTo().getGender());
        this.TxtPatientAddress.setText(this.prescription.getIssueTo().getAddress().getFormattedAddress());
    }

    private void fillDoctorData() {
        this.LblDoctorName.setText(this.LblDoctorName.getText()+ this.prescription.getPrescribedBy().getFirstName()+" "+ this.prescription.getPrescribedBy().getLastName());
        this.TxtDoctorAddress.setText(this.prescription.getPrescribedBy().getAddress().getFormattedAddress());
    }

    private void fillNotes() {
        this.TxtNotes.setText(this.prescription.getNotes());
    }

    private void fillMedicines() {
        String[] col = {"Medicine Name","Quantity","Dosage"};
        Object[][] data = new String[this.prescription.getPrescribedMedicine().size()][3];
        for(int i = 0;i<data.length;i++){
            PrescribedMedicine pm = this.prescription.getPrescribedMedicine().get(i);
            data[i][0] = pm.getMedicine().getMedicineName();
            data[i][1] = Integer.toString(pm.getQuantity());
            data[i][2] = pm.getDosage();
        }
        DefaultTableModel model = new DefaultTableModel(data,col){
            @Override
            public boolean isCellEditable(int i, int i1){return false;}
        };
        this.TblMedicines.setModel(model);
        this.TblMedicines.getColumnModel().getColumn(0).setPreferredWidth(140);//Medicine Name width
        this.TblMedicines.getColumnModel().getColumn(1).setPreferredWidth(80);//Medicine Quantity width
        this.TblMedicines.getColumnModel().getColumn(2).setPreferredWidth(420);//Medicine Doseage width
    }
}
