/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;
import patientmanagementsystem.*;
/**
 *
 * @author espow
 */
public class AppointmentPanel extends javax.swing.JPanel {

    private final Appointment Appointment;
    
    /**
     * Creates new form AppointmentPanel
     * @param Appointment
     */
    public AppointmentPanel(Appointment Appointment) {
        initComponents();
        this.Appointment = Appointment;
        fillInformation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        LblTime = new javax.swing.JLabel();
        LblDoctorName = new javax.swing.JLabel();
        LblDoctorRating = new javax.swing.JLabel();
        LblPatientName = new javax.swing.JLabel();
        TxtAddress = new javax.swing.JTextArea();

        setFont(PatientManagementSystem.getTextFont());
        setMaximumSize(new java.awt.Dimension(400, 100));
        setMinimumSize(new java.awt.Dimension(400, 100));
        setPreferredSize(new java.awt.Dimension(400, 100));
        setLayout(new java.awt.GridBagLayout());

        LblTime.setFont(PatientManagementSystem.getTextFont());
        LblTime.setText("Date:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 10, 10);
        add(LblTime, gridBagConstraints);

        LblDoctorName.setFont(PatientManagementSystem.getTextFont());
        LblDoctorName.setText("Doctor: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 15, 10);
        add(LblDoctorName, gridBagConstraints);

        LblDoctorRating.setFont(PatientManagementSystem.getTextFont());
        LblDoctorRating.setText("Rating: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 15, 10);
        add(LblDoctorRating, gridBagConstraints);

        LblPatientName.setFont(PatientManagementSystem.getTextFont());
        LblPatientName.setText("Patient: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 10, 10);
        add(LblPatientName, gridBagConstraints);

        TxtAddress.setEditable(false);
        TxtAddress.setColumns(20);
        TxtAddress.setFont(PatientManagementSystem.getTextFont());
        TxtAddress.setLineWrap(true);
        TxtAddress.setRows(4);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 15, 15);
        add(TxtAddress, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblDoctorName;
    private javax.swing.JLabel LblDoctorRating;
    private javax.swing.JLabel LblPatientName;
    private javax.swing.JLabel LblTime;
    private javax.swing.JTextArea TxtAddress;
    // End of variables declaration//GEN-END:variables

    private void fillInformation() {
        LblPatientName.setText(LblPatientName.getText()+this.Appointment.getPatient().getFirstName()+" "+this.Appointment.getPatient().getLastName());
        LblTime.setText(LblTime.getText()+PatientManagementSystem.getFormat().format(this.Appointment.getDateTime()));
        LblDoctorName.setText(LblDoctorName.getText()+this.Appointment.getDoctor().getFirstName()+" "+this.Appointment.getDoctor().getLastName());
        LblDoctorRating.setText(LblDoctorRating.getText()+this.Appointment.getDoctor().getAverageRating());
        TxtAddress.setText(this.Appointment.getDoctor().getAddress().getFormattedAddress());
    }
}
