/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;
import patientmanagementsystem.PatientManagementSystem;
/**
 *
 * @author espow
 */
public class LoginPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginPanel
     */
    public LoginPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        PfPassword = new javax.swing.JPasswordField();
        TxtUniqueID = new javax.swing.JTextField();
        JbLogin = new javax.swing.JButton();
        LblUniqueID = new javax.swing.JLabel();
        LblPassword = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(200, 125));
        setMinimumSize(new java.awt.Dimension(200, 125));
        setPreferredSize(new java.awt.Dimension(200, 125));
        setLayout(new java.awt.GridBagLayout());

        PfPassword.setFont(PatientManagementSystem.getTextFont());
        PfPassword.setMaximumSize(new java.awt.Dimension(100, 22));
        PfPassword.setMinimumSize(new java.awt.Dimension(100, 22));
        PfPassword.setName(""); // NOI18N
        PfPassword.setPreferredSize(new java.awt.Dimension(100, 22));
        PfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PfPasswordActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 15);
        add(PfPassword, gridBagConstraints);
        PfPassword.getAccessibleContext().setAccessibleName("");

        TxtUniqueID.setFont(PatientManagementSystem.getTextFont());
        TxtUniqueID.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TxtUniqueID.setToolTipText("Your user type (P for Patient,\nD for Doctor, A for Administrator,\nS for Secretary) followed\n by 4 numbers.");
        TxtUniqueID.setAutoscrolls(false);
        TxtUniqueID.setMaximumSize(new java.awt.Dimension(100, 22));
        TxtUniqueID.setMinimumSize(new java.awt.Dimension(100, 22));
        TxtUniqueID.setName("TxtUniqueID"); // NOI18N
        TxtUniqueID.setPreferredSize(new java.awt.Dimension(100, 22));
        TxtUniqueID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUniqueIDActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 15);
        add(TxtUniqueID, gridBagConstraints);

        JbLogin.setFont(PatientManagementSystem.getTextFont());
        JbLogin.setText("Log in");
        JbLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbLoginActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        add(JbLogin, gridBagConstraints);

        LblUniqueID.setFont(PatientManagementSystem.getTextFont());
        LblUniqueID.setText("Unique ID:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 15, 0, 0);
        add(LblUniqueID, gridBagConstraints);

        LblPassword.setFont(PatientManagementSystem.getTextFont());
        LblPassword.setText("Password:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 15, 0, 0);
        add(LblPassword, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void PfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PfPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PfPasswordActionPerformed

    private void TxtUniqueIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUniqueIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUniqueIDActionPerformed

    private void JbLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JbLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbLogin;
    private javax.swing.JLabel LblPassword;
    private javax.swing.JLabel LblUniqueID;
    private javax.swing.JPasswordField PfPassword;
    private javax.swing.JTextField TxtUniqueID;
    // End of variables declaration//GEN-END:variables
}
