/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import patientmanagementsystem.PatientManagementSystem;
import patientmanagementsystem.PrescribedMedicine;

/**
 *
 * @author espow
 */
public class MedicinePanel extends javax.swing.JPanel {
    String name;
    String quantity;
    String dosage;
    
    /**
     * Creates new form MedicinePanel
     * @param prescription
     */
    public MedicinePanel(PrescribedMedicine medicine) {
        this.name = medicine.getMedicine().getMedicineName();
        this.quantity = Integer.toString(medicine.getQuantity());
        this.dosage = medicine.getDosage();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        TxtMedicinceName = new javax.swing.JTextArea();
        TxtQuantity = new javax.swing.JTextArea();
        TxtDosage = new javax.swing.JTextArea();

        setMaximumSize(new java.awt.Dimension(640, 50));
        setMinimumSize(new java.awt.Dimension(640, 50));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(640, 50));
        setRequestFocusEnabled(false);
        setLayout(new java.awt.GridBagLayout());

        jSeparator1.setMaximumSize(new java.awt.Dimension(650, 1));
        jSeparator1.setMinimumSize(new java.awt.Dimension(650, 1));
        jSeparator1.setName(""); // NOI18N
        jSeparator1.setPreferredSize(new java.awt.Dimension(650, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(jSeparator1, gridBagConstraints);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setMaximumSize(new java.awt.Dimension(1, 50));
        jSeparator2.setMinimumSize(new java.awt.Dimension(1, 50));
        jSeparator2.setPreferredSize(new java.awt.Dimension(1, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(jSeparator2, gridBagConstraints);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator4.setMaximumSize(new java.awt.Dimension(1, 50));
        jSeparator4.setMinimumSize(new java.awt.Dimension(1, 50));
        jSeparator4.setPreferredSize(new java.awt.Dimension(1, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(jSeparator4, gridBagConstraints);

        TxtMedicinceName.setEditable(false);
        TxtMedicinceName.setBackground(javax.swing.UIManager.getDefaults().getColor("Panel.background"));
        TxtMedicinceName.setColumns(20);
        TxtMedicinceName.setFont(PatientManagementSystem.getTextFont());
        TxtMedicinceName.setRows(5);
        TxtMedicinceName.setText(this.name);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 15, 0);
        add(TxtMedicinceName, gridBagConstraints);

        TxtQuantity.setEditable(false);
        TxtQuantity.setBackground(javax.swing.UIManager.getDefaults().getColor("Panel.background"));
        TxtQuantity.setColumns(20);
        TxtQuantity.setFont(PatientManagementSystem.getTextFont());
        TxtQuantity.setRows(5);
        TxtQuantity.setText(this.quantity);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        add(TxtQuantity, gridBagConstraints);

        TxtDosage.setEditable(false);
        TxtDosage.setBackground(javax.swing.UIManager.getDefaults().getColor("Panel.background"));
        TxtDosage.setColumns(20);
        TxtDosage.setFont(PatientManagementSystem.getTextFont());
        TxtDosage.setRows(5);
        TxtDosage.setText(this.dosage);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 15);
        add(TxtDosage, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TxtDosage;
    private javax.swing.JTextArea TxtMedicinceName;
    private javax.swing.JTextArea TxtQuantity;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
