/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import patientmanagementsystem.PatientManagementSystem;
import Objects.Rating;

/**
 *
 * @author espow
 */
public class RatingPanel extends javax.swing.JPanel {
    private final Rating rating;
    public RatingPanel(Rating rating) {
        this.rating = rating;
        initComponents();
        loadRating();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        LblRating = new javax.swing.JLabel();
        LblComment = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtComment = new javax.swing.JTextArea();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(600, 100));
        setMinimumSize(new java.awt.Dimension(600, 100));
        setPreferredSize(new java.awt.Dimension(600, 100));
        setLayout(new java.awt.GridBagLayout());

        LblRating.setFont(PatientManagementSystem.getTextFont());
        LblRating.setText("Rating: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        add(LblRating, gridBagConstraints);

        LblComment.setFont(PatientManagementSystem.getTextFont());
        LblComment.setText("Comments:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 10);
        add(LblComment, gridBagConstraints);

        jScrollPane1.setMaximumSize(new java.awt.Dimension(300, 70));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(300, 70));

        TxtComment.setEditable(false);
        TxtComment.setColumns(20);
        TxtComment.setFont(PatientManagementSystem.getTextFont());
        TxtComment.setLineWrap(true);
        TxtComment.setRows(5);
        TxtComment.setWrapStyleWord(true);
        jScrollPane1.setViewportView(TxtComment);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 15, 15);
        add(jScrollPane1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblComment;
    private javax.swing.JLabel LblRating;
    private javax.swing.JTextArea TxtComment;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void loadRating() {
        this.LblRating.setText("Rating: "+this.rating.getStars()+"/5");
        this.TxtComment.setText(this.rating.getFeedback());
    }
}
