/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import patientmanagementsystem.PatientManagementSystem;
import patientmanagementsystem.UserTypes.Patient;
import patientmanagementsystem.UserTypes.User;

/**
 *
 * @author espow
 */
public class UserPanel extends javax.swing.JPanel {
    private final User user;
    public UserPanel(User user) {
        this.user = user;
        initComponents();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblID = new javax.swing.JLabel();
        LblLastName = new javax.swing.JLabel();
        LblFirstName = new javax.swing.JLabel();
        TxtAddress = new javax.swing.JTextArea();
        LblDOB = new javax.swing.JLabel();
        LblGender = new javax.swing.JLabel();
        LblStatus = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setMaximumSize(new java.awt.Dimension(600, 100));
        setMinimumSize(new java.awt.Dimension(600, 100));
        setPreferredSize(new java.awt.Dimension(600, 100));

        LblID.setFont(PatientManagementSystem.getTextFont());
        LblID.setText("ID: ");

        LblLastName.setFont(PatientManagementSystem.getTextFont());
        LblLastName.setText("Last name: ");

        LblFirstName.setFont(PatientManagementSystem.getTextFont());
        LblFirstName.setText("First name: ");

        TxtAddress.setEditable(false);
        TxtAddress.setBackground(javax.swing.UIManager.getDefaults().getColor("Panel.background"));
        TxtAddress.setColumns(20);
        TxtAddress.setFont(PatientManagementSystem.getTextFont());
        TxtAddress.setLineWrap(true);
        TxtAddress.setRows(4);
        TxtAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TxtAddress.setMaximumSize(new java.awt.Dimension(150, 75));
        TxtAddress.setMinimumSize(new java.awt.Dimension(102, 75));
        TxtAddress.setPreferredSize(new java.awt.Dimension(102, 75));
        TxtAddress.setRequestFocusEnabled(false);

        LblDOB.setFont(PatientManagementSystem.getTextFont());
        LblDOB.setText("DOB: ");

        LblGender.setFont(PatientManagementSystem.getTextFont());
        LblGender.setText("Gender: ");

        LblStatus.setFont(PatientManagementSystem.getTextFont());
        LblStatus.setText("Status: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblLastName)
                    .addComponent(LblFirstName)
                    .addComponent(LblID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(TxtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblDOB)
                    .addComponent(LblGender)
                    .addComponent(LblStatus))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LblDOB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LblGender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LblStatus))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LblID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LblFirstName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LblLastName)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblDOB;
    private javax.swing.JLabel LblFirstName;
    private javax.swing.JLabel LblGender;
    private javax.swing.JLabel LblID;
    private javax.swing.JLabel LblLastName;
    private javax.swing.JLabel LblStatus;
    private javax.swing.JTextArea TxtAddress;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        this.LblID.setText(this.LblID.getText()+this.user.getUniqueID());
        this.LblFirstName.setText(this.LblFirstName.getText()+this.user.getFirstName());
        this.LblLastName.setText(this.LblLastName.getText()+this.user.getLastName());
        this.TxtAddress.setText(this.user.getAddress().getFormattedAddress());
        if(!this.user.getUniqueID().contains("P")){
            this.LblDOB.setVisible(false);
            this.LblGender.setVisible(false);
            this.LblStatus.setVisible(false);
        } else {
            Patient patient = (Patient) user;
            this.LblDOB.setText(this.LblDOB.getText()+PatientManagementSystem.getFormat().format(patient.getDOB()));
            this.LblGender.setText(this.LblGender.getText()+patient.getGender());
            this.LblStatus.setText(this.LblStatus.getText()+patient.getStatus());
        }
    }
}
